config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  get '/search' => 'search#search'

  resources :subscriptions, only: [:create, :destroy]

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  resources :comments, only: [:create]

  resources :votes, only: [:create] do
    delete :reset, on: :collection
  end

  delete 'attachments/:id' => 'attachments#destroy'

  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  devise_scope :user do
    post '/register' => 'omniauth_callbacks#register'
  end

  resources :questions do
    resources :answers, shallow: true do
      patch :set_best, on: :member
    end
  end

  namespace :api do
    namespace :v1 do
      resources :profiles, only: :index do
        get :me, on: :collection
      end
      resources :questions do
        resources :answers, shallow: true
      end
    end
  end

  root to: "questions#index"

  mount ActionCable.server => '/cable'
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :answers, dependent: :destroy
  belongs_to :user
  has_many :attachments, as: :attachable, dependent: :destroy
  has_many :subscriptions, dependent: :destroy

  include Votable
  include Commentable

  validates :title, :body, presence: true

  accepts_nested_attributes_for :attachments, reject_if: :all_blank, allow_destroy: true

  default_scope { order(:created_at) }

  after_create :autosubscribe_author

  def autosubscribe_author
    Subscription.create!(user: user, question: self)
  end
end

app/controllers/api/v1/questions_controller.rb
class Api::V1::QuestionsController < Api::V1::BaseController
  authorize_resource

  def index
    @questions = Question.all
    respond_with @questions, each_serializer: QuestionsSerializer
  end

  def show
    @question = Question.find(params[:id])
    respond_with @question
  end

  def create
    respond_with(@question = current_resource_owner.questions.create(question_params))
  end

private

  def question_params
    params.require(:question).permit(:title, :body)
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :load_question, only: [:show, :destroy, :edit, :update]
  before_action :build_answer, only: [:show]
  before_action :build_comment, only: [:show]
  after_action :publish_question, only: [:create]

  respond_to :html

  authorize_resource

  def index
    respond_with(@questions = Question.all)
  end

  def show
    gon.question_id = @question.id
    gon.question_user_id = @question.user_id
    respond_with(@question)
  end

  def new
    respond_with(@question = Question.new)
  end

  def create
    respond_with(@question = current_user.questions.create(question_params))
  end

  def edit
  end

  def update
    # if current_user.author_of?(@question)
      @question.update(question_params)
      respond_with(@question)
    # end
  end

  def destroy
    # if current_user.author_of?(@question)
      respond_with(@question.destroy!)
    # end
  end

private

  def load_question
    @question = Question.find(params[:id])
  end

  def build_answer
    @answer = @question.answers.build
  end

  def build_comment
    @comment = @question.comments.build
  end

  def question_params
    params.require(:question).permit(:title, :body, attachments_attributes: [:id, :file, :_destroy])
  end

  def publish_question
    return if @question.errors.any?
    ActionCable.server.broadcast(
      'questions',
      @question.as_json(methods: :rating)
    )
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/edit.html.slim
.row
  .col-lg-6
    h1 Edit question
    = render 'errors', item: @question

    = form_for @question do |f|
      .form-group
        = f.label :title
        = f.text_field :title, class: 'form-control'
      .form-group
        = f.label :body
        = f.text_area :body, class: 'form-control'

      p= f.submit 'Save', class: 'btn btn-primary'

app/views/questions/index.html.slim
h1 Questions list

p= link_to 'Ask question', new_question_path

ul.questions-list.list-group
  - @questions.each do |question|
    li.list-group-item id="question_#{question.id}"
      - if user_signed_in? && current_user.author_of?(question)
        '
        = link_to 'Delete', question, method: :delete
      - if user_signed_in? && !current_user.author_of?(question)
        =< link_to 'Up', '#', class: 'vote-link', data: { value: 1, votable_id: question.id, votable_type: 'Question' }, style: "display: #{ question.has_vote_by?(current_user) ? 'none' : '' }"
        =< link_to 'Reset', '#', class: 'reset-vote-link', data: { votable_id: question.id, votable_type: 'Question' }, style: "display: #{ question.has_vote_by?(current_user) ? '' : 'none' }"
        =< link_to 'Down', '#', class: 'vote-link', data: { value: -1, votable_id: question.id, votable_type: 'Question' }, style: "display: #{ question.has_vote_by?(current_user) ? 'none' : '' }"

      - cache ['question_list', question] do
        p= link_to question.title, question
        p
          | Rate:
          span.badge.rate=< question.rating

app/views/questions/new.html.slim
.row.question_attachments
  .col-lg-6
    h1 New question
    = render 'errors', item: @question

    = form_for @question do |f|
      .form-group
        = f.label :title
        = f.text_field :title, class: 'form-control'
      .form-group
        = f.label :body
        = f.text_area :body, class: 'form-control'

      p Attachments:
      .attachments
        = f.fields_for :attachments, @question.attachments.build do |attachment|
          = render 'attachment_fields', f: attachment
        .links
          = link_to_add_association 'Add file', f, :attachments

      p= f.submit 'Create', class: 'btn btn-primary'

app/views/questions/show.html.slim
h1.question
  = @question.title
  - if user_signed_in? && current_user.author_of?(@question)
    '
    small= link_to 'Edit', edit_question_path(@question)
  - if user_signed_in? && !current_user.subscribed_to?(@question)
    '
    small= link_to 'Subscribe!', subscriptions_path(subscription: {question_id: @question}), method: :post, remote: true, class: 'subscription-link'
  - elsif user_signed_in? && current_user.subscribed_to?(@question)
    '
    small= link_to 'Unsubscribe!', @question.subscriptions.where(user_id: current_user.id).first, method: :delete, remote: true, class: 'subscription-link'

.errors
- cache @question do
  p= @question.body
p Attachments:
ul.question_attachments
  - @question.attachments.each do |a|
    li id="attachment_#{a.id}"
      = link_to a.file.identifier, a.file.url
      -if user_signed_in? && current_user.author_of?(@question)
          =link_to 'Delete', '', class: 'delete-attachment-link', data: { attachment_id: a.id }


hr
h3 Comments
.question_comments id="comments_section_question_#{@question.id}"
  p.notice
  ul.comments_list.list-group id="comments_question_#{@question.id}"
    = render @question.comments, cached: true

  - if user_signed_in?
    - cache ['comment_form', @question] do
      .row
        = render 'comments/comment_form', comment: @comment

hr

h3 Answers
.answers
  p.notice
  ul.answers_list.list-group
    = render @question.answers

  - if user_signed_in?
    .row
      .col-lg-4.panel.panel-default
        h3 Give an answer
        .answers_errors
        = form_for [@question, @answer], remote: true do |f|
          .form-group
            = f.label :body
            = f.text_area :body, class: 'form-control'
          p Attachments:
          .attachments
            = f.fields_for :attachments, @answer.attachments.build do |attachment|
              = render 'attachment_fields', f: attachment
            .links
              = link_to_add_association 'Add file', f, :attachments

          p= f.submit 'Create', class: 'btn btn-primary'